### ISSUE TITLE
Polar bear's body rotation cannot be altered on X axis

### ISSUE THREAD

**Issue by Carro1001** [SizableShrimp/EntityModelJson#1]
I've been messing with the mod for a bit, and noticed that the body part of the polar bear is always rotated 90 degrees, so when i tried fixing that, I noticed that it simply didn't work, but the Y and Z axis worked just fine. I didn't even mess with the ordering of the cubes or added anything yet, just changed some values.

currently looks like this (ignore the weird positioning, still fixing that)
![image](https://user-images.githubusercontent.com/47877096/131775705-512fbf88-f4c5-4a8a-9653-6c8a595968ee.png)

**Comment by SizableShrimp** [comment]
How are you rotating the X axis? Can you provide a json file?

**Comment by Carro1001** [comment]
Here's a drive link with the json file https://drive.google.com/file/d/1e1JN4nqgXlhXko6LDyy1YtGyvL0OfI1J/view?usp=sharing

**Comment by SizableShrimp** [comment]
Please let me know if this is still an issue on 1.19 and the latest version.

**Comment by Carro1001** [comment]
I'll check it out

**Comment by Carro1001** [comment]
big man still rather fucked up unfortunately, even used the blockbench plugin and the game still does this
![image](https://user-images.githubusercontent.com/47877096/177279107-5a88dd0c-59e1-4140-ae78-75bcfd9f7729.png)
